query getStreams(
  $where: Stream_filter! = {}
  $skip: Int! = 0
  $first: Int! = 10
  $orderBy: Stream_orderBy! = id
  $orderDirection: OrderDirection! = asc
) {
  result: streams(
    where: $where
    skip: $skip
    first: $first
    orderBy: $orderBy
    orderDirection: $orderDirection
  ) {
    id
    updatedAtTimestamp
    currentFlowRate
    token {
        id
        name
        symbol
    }
    sender: sender { id }
    receiver: receiver { id }
  }
}
