[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
    'super-examples/=lib/super-examples/',
    '@superfluid-finance/ethereum-contracts=lib/superfluid-protocol-monorepo/packages/ethereum-contracts'
]

[fmt]
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config